import type InsuranceServiceGroupsService from "@/services/InsuranceServiceGroupsService";
import type OrganizationRequestService from "@/services/OrganizationRequestService";
import type InsuranceServicesService from "@/services/InsuranceServicesService";
import type InsurancePaperService from "@/services/InsurancePaperService";
import type AutoRepairManService from "@/services/AutoRepairManService";
import type DynamicPageService from "@/services/DynamicPageService";
import type ContactUsService from "@/services/ContactUsService";
import type CarBrandService from "@/services/CarBrandService";
import type CarClassService from "@/services/CarClassService";
import type CarUsageService from "@/services/CarUsageService";
import type CarTypeService from "@/services/CarTypeService";
import type PaymentService from "@/services/PaymentService";
import type ResumeService from "@/services/ResumeService";
import type CouponService from "@/services/CouponService";
import type TicketService from "@/services/TicketService";
import type WalletService from "@/services/WalletService";
import type SkillService from "@/services/SkillService";
import type OrderService from "@/services/OrderService";
import type StateService from "@/services/StateService";
import type SnowaService from "@/services/SnowaService";
import type UserService from "@/services/UserService";
import type CityService from "@/services/CityService";
import type CarService from "@/services/CarService";

export interface IApiProvider {
  organizationRequests: OrganizationRequestService;
  insuranceGroups: InsuranceServiceGroupsService;
  insuranceServices: InsuranceServicesService;
  insurancePapers: InsurancePaperService;
  autoRepairMans: AutoRepairManService;
  dynamicPages: DynamicPageService;
  contactUs: ContactUsService;
  carClasses: CarClassService;
  car: CarService;
  carUsages: CarUsageService;
  carBrands: CarBrandService;
  carTypes: CarTypeService;
  payment: PaymentService;
  tickets: TicketService;
  coupon: CouponService;
  resume: ResumeService;
  wallet: WalletService;
  states: StateService;
  skills: SkillService;
  snowa: SnowaService;
  order: OrderService;
  cities: CityService;
  users: UserService;
}
